apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: siddb704/calculator:latest
        ports:
        - containerPort: 8080  # Change if your Java app listens on a different port

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: LoadBalancer
  selector:
    app: calculator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  # Must match containerPort above
